### ISSUE TITLE
Rendering issue with the Paper Doll mod

### ISSUE THREAD

**Issue by Pyrofab** [tr7zw/FirstPersonModel-Fabric#2]
When using the [paper doll mod](https://www.curseforge.com/minecraft/mc-mods/paper-doll) with this mod, in first person, the doll appears without the head.
Tested with version Paper Doll 1.0.0 and First Person Model 1.0.1.
![2019-08-14_22 32 02](https://user-images.githubusercontent.com/25536265/63054038-600f9b80-bee3-11e9-9e36-33bd55986265.png)

**Comment by tr7zw** [comment]
Not rendering the head in paperdoll was fixed, but paperdoll had a horrible design decision to remove the player body rotation and to lock it to the head(which translated to f5 and the firstpersonMod). I'll have to check the current state of their compatibility, and if this got fixed by paperdoll.

**Comment by tr7zw** [comment]
Gonna close this issue since it's a bug of Paperdoll that might or might not be fixed. Nothing really I can do about.
