### ISSUE TITLE
Sitting model position

### ISSUE THREAD

**Issue by p2aj** [tr7zw/FirstPersonModel-Fabric#39]
I noticed, through a mod that allows you to sit, but also sitting on minecarts or boats, I noticed that the position of the body model is positioned a lot behind what appears **in the 3rd person view**, which, for example, **in the minecart the legs come out almost halfway**, but **in the first person view** (with the mod active), **the feet barely come out**.

I don't know if this bug/graphical issue is so serious but if the mod owner can do something about it, it would be nice.

**Comment by SemmieboyYT** [comment]
That's actually a feature, the body is offsetted behind the camera a little because otherwise if you look down you would just look at your neck. You can change the offset in the settings.

**Comment by tr7zw** [comment]
If it still feels wrong after changing the settings of the normal offset I could also look into adding config options for custom sitting offsets, but I can't guarantee that it works 100% with other mods that via some way allow you to sit.

**Comment by LostMatter** [comment]
just do it
