### ISSUE TITLE
Paper Doll direction may be wrong when flying/elytra diving

### ISSUE THREAD

**Issue by somebody1234** [tr7zw/FirstPersonModel-Fabric#53]
I think when in flight, paperdoll is always pointed north or something

**Comment by tr7zw** [comment]
Yes, the paperdoll's rotation gets locked during flight because else it's completely unlocked and rotates in really odd ways. To see how it would look otherwise you can open your inventory mid-flight(the player inside the inventory uses the kinda same code, just missing some fixes).

**Comment by somebody1234** [comment]
@tr7zw The problem is that it's locked in the wrong position from the very start, shouldn't it at least point it in the direction I'm currently facing?

**Comment by tr7zw** [comment]
It should point towards yourself like it always does? (I mean what would be the direction in the sense of the GUI) Or are you using forge and there is still a deeper issue in the forge version?

**Comment by somebody1234** [comment]
I'm using fabric. I'm just running around indoors and it always faces north once I enter elytra flight.

**Comment by tr7zw** [comment]
[Image](https://tr7zw.dev/u/1608997666.png) I'm not sure what you mean? The only noteworthy thing I see is that the roll is the same, so when flying straight down your upside down on the paper doll (which is technically correct), but the yaw/rotation is as expected?

**Comment by tr7zw** [comment]
Maybe you can join the discord so we can better communicate about this^^?

**Comment by tr7zw** [comment]
Fixed :)
