### ISSUE TITLE
head doesn't show on shadows with shaders and this mod installed

### ISSUE THREAD

**Issue by Nathan22211** [tr7zw/FirstPersonModel-Fabric#7]

**Comment by Kaydax** [comment]
bump, I would love for this to be fixed

**Comment by tr7zw** [comment]
I have no clue if this is fixable, but according to https://www.curseforge.com/minecraft/mc-mods/first-person-model?comment=34 the forge mod Advanced Skin Customization somehow is able to do it. I'll have to look into how he as done it, but probably you have to somehow re-enable the head after rendering the body, but before the shader is getting its data.

**Comment by KosmX** [comment]
I have fixed the bug!!!
First I tried to turn it visible immediately after the render but id didn't work.
The optifine renders everything twice, one normally one shader.
My repository is [https://github.com/KosmX/FirstPersonModel-Fabric](https://github.com/KosmX/FirstPersonModel-Fabric)

I fixed another bug: if I don't have a helmet one will randomly disappear.

**Comment by tr7zw** [comment]
Oh neat. Open a pull request(or I will) and then I'll check out the changes and release the fixed version 👍

**Comment by KosmX** [comment]
I opened a pull request.
